PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE EQUIPA
   (	IDEQUIPA TEXT,
	NOME TEXT,
	CLASSIFICACAO INT,
	PONTOS INT,
	NUMJOGOS INT,
	GOLOSMARCADOS INT,
	GOLOSSOFRIDOS INT,
	DIFERENCAGOLOS INT,
    PRIMARY KEY (IDEQUIPA));

CREATE TABLE JOGADOR
	(
	IDJOGADOR TEXT,
	NOME TEXT,
	IDADE INT,
	NUMERO INT,
	NACIONALIDADE TEXT,
	NUMGOLOS INT,
	NUMASSISTENCIAS INT,
	NUMAMARELOS INT,
	IDEQUIPA TEXT,
    PRIMARY KEY (IDJOGADOR), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA));

CREATE TABLE EPOCA
	(
	IDEPOCA TEXT,
	ANO INT,
	PRIMARY KEY(IDEPOCA)
);

CREATE TABLE JOGO
	(
	IDJOGO TEXT,
	JORNADA INT,
	DIA DATE,
	RESULTADO TEXT,
	PRIMARY KEY (IDJOGO)
);

CREATE TABLE JOGOEQUIPAEPOCA
	(
	IDJOGO TEXT,
	IDEPOCA TEXT,
	IDEQUIPA TEXT,
	IDEQUIPA2 TEXT,
	PRIMARY KEY(IDJOGO,IDEPOCA), FOREIGN KEY (IDEQUIPA,IDEQUIPA2) REFERENCES EQUIPA(IDEQUIPA,IDEQUIPA)
);

CREATE TABLE EQUIPAARBITRAGEM
	(
	IDEQUIPAARBITRAGEM TEXT,
	ARBITRO_PRINCIPAL TEXT,
	ARBITROLINHA1 TEXT,
	ARBITROLINHA2 TEXT,
	ARBITRO4 TEXT,
	VARPRINCIPAL TEXT,
	VARASSISTENTE TEXT,
	PRIMARY KEY(IDEQUIPAARBITRAGEM)
);

CREATE TABLE EQUIPATECNICA
	(
	IDEQUIPATECNICA TEXT,
	TREINADORPRINCIPAL TEXT,
	TREINADORADJUNTO TEXT,
	TREINADORGR TEXT,
	DIRETORDESPORTIVO TEXT,
	ANALISTA TEXT,
	IDEQUIPA TEXT,
	PRIMARY KEY(IDEQUIPATECNICA), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE ESTADIO
	(
	IDESTADIO TEXT,
	NOME TEXT,
	LOCALIZACAO TEXT,
	CAPACIDADE BIGINT,
	PRIMARY KEY(IDESTADIO)
);

CREATE TABLE ESTATISTICAS
	(
	IDESTATISTICAS TEXT,
	POSSEBOLA FLOAT,
	CANTOS INT,
	LIVRES INT,
	REMATES INT,
	REMATESCOLOCADOS INT,
	IDEQUIPA TEXT,
	PRIMARY KEY (IDESTATISTICAS), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE GOLO
	(
	IDGOLO TEXT,
	MINUTO TIME,
	DESCRICAO TEXT,
	IDJOGADOR TEXT,
	PRIMARY KEY (IDGOLO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);

CREATE TABLE OUTRO
	(
	IDOUTRO TEXT,
	MINUTO TIME,
	DESCRICAO TEXT,
	IDJOGADOR TEXT,
	PRIMARY KEY(IDOUTRO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);

CREATE TABLE SUBSTITUICAO
	(
	IDSUBSTITUICAO TEXT,
	MINUTO TIME,
	IDJOGADORENTRA TEXT,
	IDJOGADORSAI TEXT,
	PRIMARY KEY(IDSUBSTITUICAO), FOREIGN KEY (IDJOGADORENTRA,IDJOGADORSAI) REFERENCES JOGADOR(IDJOGADOR,IDJOGADOR)
);

CREATE TABLE CARTAO
	(
	IDCARTAO TEXT,
	MINUTO TIME,
	COR TEXT,
	IDJOGADOR TEXT,
	PRIMARY KEY(IDCARTAO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);

CREATE TABLE ENTRADACOPALIBERTADORES
	(
	IDENTRADACOPALIBERTADORES TEXT,
	IDEQUIPA TEXT,
	PRIMARY KEY(IDENTRADACOPALIBERTADORES), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE ENTRADACOPASULAMERICANA
	(
	IDENTRADACOPASULAMERICANA TEXT,
	IDEQUIPA TEXT,
	PRIMARY KEY(IDENTRADACOPASULAMERICANA), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE DESPROMOCAO
	(
	IDDESPROMOCAO TEXT,
	IDEQUIPA TEXT,
	PRIMARY KEY(IDDESPROMOCAO), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);