.mode columns
.headers on
.nullvalue NULL

SELECT JOGO.RESULTADO as RESULTADO, JOGOEQUIPAEPOCA.IDEQUIPACASA AS IDEQUIPACASA, 
JOGOEQUIPAEPOCA.IDEQUIPAVISITANTE AS IDEQUIPAVISITANTE
FROM JOGO, JOGOEQUIPAEPOCA, EQUIPA WHERE JOGOEQUIPAEPOCA.IDEQUIPACASA == EQUIPA.IDEQUIPA AND JOGOEQUIPAEPOCA.IDEQUIPAVISITANTE == EQUIPA.IDEQUIPA
AND JOGOEQUIPAEPOCA.IDJOGO == JOGO.IDJOGO AND
SUBSTR(RESULTADO, 1, 1) == SUBSTR(RESULTADO, 3, 1) AND JOGO.JORNADA >= 1 AND JOGO.JORNADA <= 190