.mode columns
.headers on
.nullvalue NULL

SELECT JOGADOR.NOME AS "Nome", EQUIPA.NOME AS "Equipa"
FROM JOGADOR 
JOIN EQUIPA ON JOGADOR.IDEQUIPA = EQUIPA.IDEQUIPA
WHERE JOGADOR.NOME LIKE "%Silva%"
ORDER BY 1