.mode columns
.headers on
.nullvalue NULL

SELECT EQUIPA.NOME AS EQUIPA, ENTRADACOPALIBERTADORES.CLASSIFICACAO AS CLASSIFICACAO, 
EQUIPA.PONTOS as PONTOS
FROM ENTRADACOPALIBERTADORES JOIN
EQUIPA ON ENTRADACOPALIBERTADORES.IDEQUIPA = EQUIPA.IDEQUIPA