.mode columns
.headers on
.nullvalue NULL

SELECT EQUIPA.NOME AS "Equipa", ENTRADACOPALIBERTADORES.CLASSIFICACAO AS "Classificação", EQUIPA.PONTOS as "Pontos"
FROM ENTRADACOPALIBERTADORES 
JOIN EQUIPA ON ENTRADACOPALIBERTADORES.IDEQUIPA = EQUIPA.IDEQUIPA