PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS EQUIPA;
DROP TABLE IF EXISTS JOGADOR;
DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS EPOCA;
DROP TABLE IF EXISTS JOGOEQUIPAEPOCA;
DROP TABLE IF EXISTS ESTATISTICAS;
DROP TABLE IF EXISTS GOLO;
DROP TABLE IF EXISTS OUTRO;
DROP TABLE IF EXISTS CARTAO;
DROP TABLE IF EXISTS SUBSTITUICAO;
DROP TABLE IF EXISTS ENTRADACOPALIBERTADORES;
DROP TABLE IF EXISTS QUALIFICACAOCOPALIBERTADORES;
DROP TABLE IF EXISTS ENTRADACOPASULAMERICANA;
DROP TABLE IF EXISTS DESPROMOCAO;

CREATE TABLE EQUIPA
   (	
	IDEQUIPA TEXT NOT NULL,
	NOME TEXT NOT NULL,
	CLASSIFICACAO INT NOT NULL,
	PONTOS INT NOT NULL,
	NUMJOGOS INT NOT NULL,
	GOLOSMARCADOS INT NOT NULL,
	GOLOSSOFRIDOS INT NOT NULL,
	DIFERENCAGOLOS INT NOT NULL,
    PRIMARY KEY (IDEQUIPA));

CREATE TABLE JOGADOR
	(
	IDJOGADOR TEXT NOT NULL,
	NOME TEXT NOT NULL,
	IDADE INT NOT NULL,
	NUMERO INT NOT NULL,
	POSICAO TEXT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
    PRIMARY KEY (IDJOGADOR), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA));

CREATE TABLE EPOCA
	(
	IDEPOCA TEXT NOT NULL,
	ANO INT NOT NULL,
	PRIMARY KEY(IDEPOCA)
);

CREATE TABLE JOGO
	(
	IDJOGO TEXT NOT NULL,
	JORNADA INT NOT NULL,
	DIA DATE NOT NULL,
	RESULTADO TEXT NOT NULL,
	ESTADIO TEXT NOT NULL,
	PRIMARY KEY (IDJOGO)
);

CREATE TABLE JOGOEQUIPAEPOCA
	(
	IDJOGO TEXT NOT NULL,
	IDEPOCA TEXT NOT NULL,
	IDEQUIPACASA TEXT NOT NULL,
	IDEQUIPAVISITANTE TEXT NOT NULL,
	PRIMARY KEY(IDJOGO,IDEPOCA), FOREIGN KEY (IDEQUIPACASA) REFERENCES EQUIPA(IDEQUIPA), 
	FOREIGN KEY (IDEQUIPAVISITANTE) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE ESTATISTICAS
	(
	IDESTATISTICAS TEXT NOT NULL,
	POSSEBOLA INT NOT NULL,
	CANTOS INT NOT NULL,
	LIVRES INT NOT NULL,
	REMATES INT NOT NULL,
	REMATESCOLOCADOS INT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
	IDJOGO INT NOT NULL,
	PRIMARY KEY (IDESTATISTICAS), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA),
	FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO)
);

CREATE TABLE GOLO
	(
	IDGOLO TEXT NOT NULL,
	MINUTO INT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	IDJOGADOR TEXT NOT NULL,
	IDJOGO INT NOT NULL,
	PRIMARY KEY (IDGOLO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR),
	FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO)
);

CREATE TABLE OUTRO
	(
	IDOUTRO TEXT NOT NULL,
	MINUTO INT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	IDJOGADOR TEXT NOT NULL,
	IDJOGO INT NOT NULL,
	PRIMARY KEY(IDOUTRO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR),
	FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO)
);

CREATE TABLE SUBSTITUICAO
	(
	IDSUBSTITUICAO TEXT NOT NULL,
	MINUTO INT NOT NULL,
	IDJOGADORENTRA TEXT NOT NULL,
	IDJOGADORSAI TEXT NOT NULL,
	IDJOGO INT NOT NULL,
	PRIMARY KEY(IDSUBSTITUICAO), FOREIGN KEY (IDJOGADORENTRA) REFERENCES JOGADOR(IDJOGADOR),
	FOREIGN KEY (IDJOGADORSAI) REFERENCES JOGADOR(IDJOGADOR),
	FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO)
);

CREATE TABLE CARTAO
	(
	IDCARTAO TEXT NOT NULL,
	MINUTO INT NOT NULL,
	COR TEXT NOT NULL,
	IDJOGADOR TEXT NOT NULL,
	IDJOGO INT NOT NULL,
	PRIMARY KEY(IDCARTAO), FOREIGN KEY (IDJOGADOR) REFERENCES JOGADOR(IDJOGADOR),
	FOREIGN KEY (IDJOGO) REFERENCES JOGO(IDJOGO)
);

CREATE TABLE ENTRADACOPALIBERTADORES
	(
	IDENTRADACOPALIBERTADORES TEXT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
	PRIMARY KEY(IDENTRADACOPALIBERTADORES), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE QUALIFICACAOCOPALIBERTADORES
	(
	IDQUALIFICACAOCOPALIBERTADORES TEXT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
	PRIMARY KEY(IDQUALIFICACAOCOPALIBERTADORES), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE ENTRADACOPASULAMERICANA
	(
	IDENTRADACOPASULAMERICANA TEXT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
	PRIMARY KEY(IDENTRADACOPASULAMERICANA), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);

CREATE TABLE DESPROMOCAO
	(
	IDDESPROMOCAO TEXT NOT NULL,
	IDEQUIPA TEXT NOT NULL,
	PRIMARY KEY(IDDESPROMOCAO), FOREIGN KEY (IDEQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);
